apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lbo3ec94y-nodejs 
  janus-idp.io/tekton: lbo3ec94y-nodejs
  backstage.io/kubernetes-id: lbo3ec94y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lbo3ec94y-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  